const mongoose = require("mongoose");
// Connect to the Mongo DB
mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/words");

const words = [
  {
    name: "words",
    description: "easyWords",
    easy: [
      "not",
      "me",
      "are",
      "all",
      "ate",
      "a",
      "I",
      "with",
      "and",
      "away",
      "be",
      "big",
      "black",
      "brown",
      "but",
      "blue",
      "came",
      "can",
      "come",
      "did",
      "do",
      "down",
      "eat",
      "fat",
      "find",
      "four",
      "for",
      "funny",
      "get",
      "go",
      "good",
      "had",
      "has",
      "have",
      "he",
      "help",
      "here",
      "here",
      "in",
      "into",
      "is",
      "it",
      "jump",
      "like",
      "little",
      "look",
      "make",
      "may",
      "my",
      "of",
      "on",
      "out",
      "our",
      "one",
      "play",
      "please",
      "pretty",
      "put",
      "ran",
      "red",
      "ride",
      "round",
      "run",
      "said",
      "see",
      "the",
      "three",
      "to",
      "two",
      "under",
      "up",
      "we",
      "where",
      "yellow",
      "you",
    ],
  },
];
